export const NUMBER = 'number'
export const IDENTIFIER = 'identifier'
export const FUNCTION_CALL = 'functionCall'
export const UNARY = 'unary'
export const BINARY = 'binary'
export const ASSIGNMENT = 'assignment'
export const EXPRESSION = 'expression'
